/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Generic BSD <sys/tree.h>-style red-black tree macros for the HAMMER2 Linux
 * port, implemented on top of Linux's <linux/rbtree.h>.
 *
 * DragonFly's <sys/tree.h> RB_GENERATE() emits type-specific functions using
 * its own intrusive node layout (rbe_left/right/parent/color).  On Linux we
 * cannot use that layout directly, so these macros generate equivalent
 * type-specific functions (name##_RB_*) backed by struct rb_node / rb_root.
 * This keeps every tree element's node as a plain struct rb_node (so element
 * struct layouts are unchanged across translation units) while still letting
 * multiple distinct trees be generated -- the per-core chain tree
 * (hammer2_chain_tree) and the kdmsg message-state trees (kdmsg_state_tree).
 *
 * Semantics match the subset of <sys/tree.h> that HAMMER2 + kern_dmsg use:
 *   - cmp(a, b) returns <0, 0, >0 (overlap counts as a match / collision).
 *   - RB_INSERT returns NULL on success or the colliding element.
 *   - RB_SCAN(name, head, scancmp, callback, arg): scancmp==NULL visits every
 *     node; otherwise scancmp(node,arg) returns <0 (node before range), >0
 *     (after range), 0 (in range) and callback() is invoked for each in-range
 *     node.  callback() returns >=0 to continue (its value is summed into the
 *     RB_SCAN return count) or <0 to stop.  The in-order successor is fetched
 *     before callback() so the callback may unlink the node it is handed.
 */

#ifndef _FS_HAMMER2_RB_H_
#define _FS_HAMMER2_RB_H_

#include "hammer2_rbtree_windows.h"

#define RB_HEAD(name, type)		struct name { struct rb_root rbh_root; }
#define RB_ENTRY(type)			struct rb_node
#ifdef _WIN32
/* MSVC rejects the (struct rb_root)RB_ROOT self-cast; assign the member. */
#define RB_INITIALIZER(root)		{ { NULL } }
#define RB_INIT(head)			do { (head)->rbh_root.rb_node = NULL; } while (0)
#else
#define RB_INITIALIZER(root)		{ RB_ROOT }
#define RB_INIT(head)			do { (head)->rbh_root = (struct rb_root)RB_ROOT; } while (0)
#endif
#define RB_EMPTY(head)			RB_EMPTY_ROOT(&(head)->rbh_root)

/*
 * Prototypes for the type-specific accessors generated by RB_GENERATE().
 * RB_PROTOTYPE_SCAN / RB_GENERATE_SCAN are folded into the base macros (the
 * scan function is always generated), so the *_SCAN variants are no-ops kept
 * for source compatibility with call sites that invoke them separately.
 */
#define RB_PROTOTYPE(name, type, field, cmp)				\
	struct type *name##_RB_INSERT(struct name *, struct type *);	\
	struct type *name##_RB_FIND(struct name *, struct type *);	\
	void  name##_RB_REMOVE(struct name *, struct type *);		\
	struct type *name##_RB_MINMAX(struct name *, int);		\
	struct type *name##_RB_NEXT(struct type *);			\
	struct type *name##_RB_PREV(struct type *);			\
	int   name##_RB_SCAN(struct name *,				\
		int (*)(struct type *, void *),				\
		int (*)(struct type *, void *), void *)
#define RB_PROTOTYPE_SCAN(name, type, field)	/* folded into RB_PROTOTYPE */

#define RB_GENERATE(name, type, field, cmp)				\
struct type *name##_RB_INSERT(struct name *head, struct type *elm)	\
{									\
	struct rb_node **_pp = &head->rbh_root.rb_node;			\
	struct rb_node *_par = NULL;					\
	struct type *_cur;						\
	int _c;								\
	while (*_pp) {							\
		_par = *_pp;						\
		_cur = rb_entry(_par, struct type, field);		\
		_c = cmp(elm, _cur);					\
		if (_c < 0)						\
			_pp = &(*_pp)->rb_left;				\
		else if (_c > 0)					\
			_pp = &(*_pp)->rb_right;			\
		else							\
			return (_cur);	/* collision */			\
	}								\
	rb_link_node(&elm->field, _par, _pp);				\
	rb_insert_color(&elm->field, &head->rbh_root);			\
	return (NULL);							\
}									\
struct type *name##_RB_FIND(struct name *head, struct type *elm)	\
{									\
	struct rb_node *_n = head->rbh_root.rb_node;			\
	struct type *_cur;						\
	int _c;								\
	while (_n) {							\
		_cur = rb_entry(_n, struct type, field);		\
		_c = cmp(elm, _cur);					\
		if (_c < 0)						\
			_n = _n->rb_left;				\
		else if (_c > 0)					\
			_n = _n->rb_right;				\
		else							\
			return (_cur);					\
	}								\
	return (NULL);							\
}									\
void name##_RB_REMOVE(struct name *head, struct type *elm)		\
{									\
	rb_erase(&elm->field, &head->rbh_root);				\
}									\
struct type *name##_RB_MINMAX(struct name *head, int dir)		\
{									\
	struct rb_node *_n = (dir < 0) ? rb_first(&head->rbh_root)	\
				       : rb_last(&head->rbh_root);	\
	return (_n ? rb_entry(_n, struct type, field) : NULL);		\
}									\
struct type *name##_RB_NEXT(struct type *elm)				\
{									\
	struct rb_node *_n = rb_next(&elm->field);			\
	return (_n ? rb_entry(_n, struct type, field) : NULL);		\
}									\
struct type *name##_RB_PREV(struct type *elm)				\
{									\
	struct rb_node *_n = rb_prev(&elm->field);			\
	return (_n ? rb_entry(_n, struct type, field) : NULL);		\
}									\
int name##_RB_SCAN(struct name *head,					\
	int (*scancmp)(struct type *, void *),				\
	int (*callback)(struct type *, void *), void *arg)		\
{									\
	struct rb_node *_n, *_next, *_best;				\
	struct type *_e;						\
	int _c, _count = 0;						\
	if (scancmp == NULL) {						\
		for (_n = rb_first(&head->rbh_root); _n; _n = _next) {	\
			_e = rb_entry(_n, struct type, field);		\
			_next = rb_next(_n);				\
			_c = callback(_e, arg);				\
			if (_c < 0) { _count = _c; break; }		\
			_count += _c;					\
		}							\
		return (_count);					\
	}								\
	_n = head->rbh_root.rb_node;					\
	_best = NULL;							\
	while (_n) {							\
		_e = rb_entry(_n, struct type, field);			\
		_c = scancmp(_e, arg);					\
		if (_c < 0) {						\
			_n = _n->rb_right;				\
		} else {						\
			_best = _n;					\
			if (_n->rb_left == NULL)			\
				break;					\
			_n = _n->rb_left;				\
		}							\
	}								\
	for (_n = _best; _n; _n = _next) {				\
		_e = rb_entry(_n, struct type, field);			\
		_next = rb_next(_n);					\
		if (scancmp(_e, arg) > 0)				\
			break;						\
		_c = callback(_e, arg);					\
		if (_c < 0) { _count = _c; break; }			\
		_count += _c;						\
	}								\
	return (_count);						\
}									\
struct __##name##_rb_semicolon_eater
#define RB_GENERATE_SCAN(name, type, field)	/* folded into RB_GENERATE */

#define RB_INSERT(name, head, elm)	name##_RB_INSERT(head, elm)
#define RB_FIND(name, head, elm)	name##_RB_FIND(head, elm)
#define RB_REMOVE(name, head, elm)	name##_RB_REMOVE(head, elm)
#define RB_SCAN(name, head, cmp, cb, arg) name##_RB_SCAN(head, cmp, cb, arg)
#define RB_MIN(name, head)		name##_RB_MINMAX(head, -1)
#define RB_MAX(name, head)		name##_RB_MINMAX(head, 1)
#define RB_NEXT(name, head, elm)	name##_RB_NEXT(elm)
#define RB_PREV(name, head, elm)	name##_RB_PREV(elm)
#define RB_FOREACH(x, name, head)					\
	for ((x) = name##_RB_MINMAX(head, -1); (x) != NULL;		\
	     (x) = name##_RB_NEXT(x))

#endif /* !_FS_HAMMER2_RB_H_ */
